default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  host: 'localhost'
  username: 'baral_db'
  password: 'baral_db'
  database: baral_development_db

production:
  <<: *default
  database: 'baral-production-db'
  username: 'baral'
  password: 'baral'
  host: '13.127.91.212'
  port: 5432
